//
// Generated file, do not edit! Created by opp_msgc 4.1 from flowRegReq.msg.
//

#ifndef _FLOWREGREQ_M_H_
#define _FLOWREGREQ_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>flowRegReq.msg</tt> by opp_msgc.
 * <pre>
 * packet FlowRegReq {
 *     int flow;
 *     int dest;
 *     int source;
 * }
 * </pre>
 */
class FlowRegReq : public ::cPacket
{
  protected:
    int flow_var;
    int dest_var;
    int source_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FlowRegReq&);

  public:
    FlowRegReq(const char *name=NULL, int kind=0);
    FlowRegReq(const FlowRegReq& other);
    virtual ~FlowRegReq();
    FlowRegReq& operator=(const FlowRegReq& other);
    virtual FlowRegReq *dup() const {return new FlowRegReq(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getFlow() const;
    virtual void setFlow(int flow_var);
    virtual int getDest() const;
    virtual void setDest(int dest_var);
    virtual int getSource() const;
    virtual void setSource(int source_var);
};

inline void doPacking(cCommBuffer *b, FlowRegReq& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, FlowRegReq& obj) {obj.parsimUnpack(b);}


#endif // _FLOWREGREQ_M_H_
