//
// Generated file, do not edit! Created by opp_msgc 4.1 from peerRegister.msg.
//

#ifndef _PEERREGISTER_M_H_
#define _PEERREGISTER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>peerRegister.msg</tt> by opp_msgc.
 * <pre>
 * message PeerRegister {
 *     int id;
 *     int type;
 * }
 * </pre>
 */
class PeerRegister : public ::cMessage
{
  protected:
    int id_var;
    int type_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PeerRegister&);

  public:
    PeerRegister(const char *name=NULL, int kind=0);
    PeerRegister(const PeerRegister& other);
    virtual ~PeerRegister();
    PeerRegister& operator=(const PeerRegister& other);
    virtual PeerRegister *dup() const {return new PeerRegister(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id_var);
    virtual int getType() const;
    virtual void setType(int type_var);
};

inline void doPacking(cCommBuffer *b, PeerRegister& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PeerRegister& obj) {obj.parsimUnpack(b);}


#endif // _PEERREGISTER_M_H_
