//
// Generated file, do not edit! Created by opp_msgc 4.1 from streamResponse.msg.
//

#ifndef _STREAMRESPONSE_M_H_
#define _STREAMRESPONSE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>streamResponse.msg</tt> by opp_msgc.
 * <pre>
 * message StreamResponse {
 *     int provider;
 *     int dest;
 *     int stream;
 * }
 * </pre>
 */
class StreamResponse : public ::cMessage
{
  protected:
    int provider_var;
    int dest_var;
    int stream_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StreamResponse&);

  public:
    StreamResponse(const char *name=NULL, int kind=0);
    StreamResponse(const StreamResponse& other);
    virtual ~StreamResponse();
    StreamResponse& operator=(const StreamResponse& other);
    virtual StreamResponse *dup() const {return new StreamResponse(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getProvider() const;
    virtual void setProvider(int provider_var);
    virtual int getDest() const;
    virtual void setDest(int dest_var);
    virtual int getStream() const;
    virtual void setStream(int stream_var);
};

inline void doPacking(cCommBuffer *b, StreamResponse& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, StreamResponse& obj) {obj.parsimUnpack(b);}


#endif // _STREAMRESPONSE_M_H_
