//
// Generated file, do not edit! Created by opp_msgc 4.1 from streamRegReq.msg.
//

#ifndef _STREAMREGREQ_M_H_
#define _STREAMREGREQ_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>streamRegReq.msg</tt> by opp_msgc.
 * <pre>
 * packet StreamRegReq {
 *     int stream;
 *     int dest;
 *     int source;
 * }
 * </pre>
 */
class StreamRegReq : public ::cPacket
{
  protected:
    int stream_var;
    int dest_var;
    int source_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StreamRegReq&);

  public:
    StreamRegReq(const char *name=NULL, int kind=0);
    StreamRegReq(const StreamRegReq& other);
    virtual ~StreamRegReq();
    StreamRegReq& operator=(const StreamRegReq& other);
    virtual StreamRegReq *dup() const {return new StreamRegReq(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getStream() const;
    virtual void setStream(int stream_var);
    virtual int getDest() const;
    virtual void setDest(int dest_var);
    virtual int getSource() const;
    virtual void setSource(int source_var);
};

inline void doPacking(cCommBuffer *b, StreamRegReq& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, StreamRegReq& obj) {obj.parsimUnpack(b);}


#endif // _STREAMREGREQ_M_H_
